#!/usr/bin/env zsh

# ========================================================================================
# SSH Keys
# ========================================================================================

printf "${FG_MAGENTA}==> [OpenSSH] Generating SSH keys${RESET}\n"

ssh_generate_key

if [[ ! -r ~/.ssh/config ]]; then
  touch ~/.ssh/config
fi

cat >> ~/.ssh/config <<EOF
Host *
  IgnoreUnknown UseKeychain
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
EOF

printf "Done.\n\n"
