#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# SSH Keys
# ========================================================================================

printf "${BOLD}${PURPLE}==> [OpenSSH]${NORMAL} ${BOLD}Generating SSH keys${NORMAL}\n"

ssh_generate_key

printf "Done.\n\n"
