#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# SSH Keys
# ========================================================================================

printf "${BOLD}${PURPLE}==> [OpenSSH]${NORMAL} ${BOLD}Generating SSH keys${NORMAL}\n"

ssh_generate_key

if [[ ! -r ~/.ssh/config ]]; then
  touch ~/.ssh/config
fi

cat >> ~/.ssh/config <<EOF
Host *
  UseKeychain yes
  AddKeysToAgent yes
  IdentityFile ~/.ssh/id_rsa
EOF

printf "Done.\n\n"
