#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# Variables
# ========================================================================================

extensions=(
  "mrmlnc.vscode-apache"
  "iampeterbanjo.elixirlinter"
  "jakebecker.elixir-ls"
  "craigmaslowski.erb"
  "dbaeumer.vscode-eslint"
  "github.vscode-pull-request-github"
  "eamodio.gitlens"
  "mjmlio.vscode-mjml"
  "zhuangtongfa.material-theme"
  "mhmadhamster.postcss-language"
  "rebornix.ruby"
  "castwide.solargraph"
  "octref.vetur"
  "wingrunr21.vscode-ruby"
  "sdras.vue-vscode-snippets"
  "redhat.vscode-yaml"
)

# ========================================================================================
# Helpers
# ========================================================================================

install_extensions() {
  for extension in ${extensions[@]}; do
    printf "${BOLD}${PURPLE}==> [VS Code]${NORMAL} ${BOLD}Installing extension ${GREEN}${extension}${NORMAL}\n"

    if [[ $(code --list-extensions | grep -i ${extension}) ]]; then
      printf "Extension installed.\n"
    else
      code --install-extension ${extension}
    fi

    printf "\n"
  done
  unset extension
}

# ========================================================================================
# VS Code
# ========================================================================================

# configure settings
# keybindings.json
# settings.json

install_extensions
