#!/usr/bin/env zsh

# ========================================================================================
# Helpers
# ========================================================================================

# lookup dns records
alias dnsrecords="host -a"

# flush dns cache
alias flushdns="dscacheutil -flushcache && killall -HUP mDNSResponder"

# edit hostfile
alias hosts="edit /etc/hosts"

# get IP address
alias ip="wget https://ipinfo.io/ip -qO -"

# get local IP address
alias localip="ipconfig getifaddr en0"
