#!/usr/bin/env zsh

# ========================================================================================
# Variables
# ========================================================================================

formulae=(
  "asdf"
  "coreutils"
  "exa"
  "findutils"
  "fzf"
  "gh"
  "git"
  "gnupg"
  "grep"
  "imagemagick"
  "node"
  "openssh"
  "pinentry-mac"
  "ripgrep"
  "wget"
  "yarn"
  "zsh"
  "zsh-completions"
  "zsh-syntax-highlighting"
)

applications=(
  "1password"
  "adguard"
  "brave-browser"
  "cleanmymac"
  "figma"
  "firefox"
  "fliqlo"
  "github"
  "iina"
  "imageoptim"
  "iterm2"
  "ledger-live"
  "little-snitch"
  "notion"
  "pocket-casts"
  "postgres-unofficial"
  "postico"
  "slack"
  "tidal"
  "tor-browser"
  "transmission"
  "visual-studio-code"
  "zoom"
)

drivers=(
  "wacom-tablet"
)

fonts=(
  "font-inter"
  "font-jetbrains-mono"
)

# ========================================================================================
# Helpers
# ========================================================================================

install_homebrew() {
  printf "${FG_MAGENTA}==> [Homebrew] Installing${RESET}\n"

  if [[ $(which brew) ]]; then
    printf "Homebrew installed.\n\n"

    printf "${FG_MAGENTA}==> [Homebrew] Updating${RESET}\n"
    brew update
    brew upgrade
    printf "\n"
  else
    /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    brew tap homebrew/cask-versions
    brew tap homebrew/cask-drivers
    brew tap homebrew/cask-fonts

    brew services

    brew analytics off
  fi
}

install_formulae() {
  for formula in ${formulae[@]}; do
    printf "${FG_MAGENTA}==> [Homebrew] Installing formula ${FG_BOLD_GREEN}${formula}${RESET}\n"

    if [[ $(brew list --versions ${formula} 2> /dev/null) ]]; then
      printf "Formula installed.\n"
    else
      brew install ${formula}
    fi

    printf "\n"
  done
  unset formula
}

install_applications() {
  for application in ${applications[@]}; do
    printf "${FG_MAGENTA}==> [Homebrew] Installing application ${FG_BOLD_GREEN}${application}${RESET}\n"

    if [[ $(brew cask list --versions ${application} 2> /dev/null) ]]; then
      printf "Application installed.\n"
    else
      brew install --cask ${application}
    fi

    printf "\n"
  done
  unset application
}

install_drivers() {
  for driver in ${drivers[@]}; do
    printf "${FG_MAGENTA}==> [Homebrew] Installing driver ${FG_BOLD_GREEN}${driver}${RESET}\n"

    if [[ $(brew cask list --versions ${driver} 2> /dev/null) ]]; then
      printf "Driver installed.\n"
    else
      brew install --cask ${driver}
    fi

    printf "\n"
  done
  unset driver
}

install_fonts() {
  for font in ${fonts[@]}; do
    printf "${FG_MAGENTA}==> [Homebrew] Installing font ${FG_BOLD_GREEN}${font}${RESET}\n"

    if [[ $(brew cask list --versions ${font} 2> /dev/null) ]]; then
      printf "Font installed.\n"
    else
      brew install --cask ${font}
    fi

    printf "\n"
  done
  unset font
}

# ========================================================================================
# Homebrew
# ========================================================================================

install_homebrew
install_formulae
install_applications
install_drivers
install_fonts

printf "${FG_MAGENTA}==> [Homebrew] Cleaning up${RESET}\n"
brew cleanup
printf "Done.\n\n"
