#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# Variables
# ========================================================================================

formulae=(
  "asdf"
  "awscli"
  "bash"
  "bash-completion@2"
  "coreutils"
  "docker"
  "exa"
  "findutils"
  "fzf"
  "gh"
  "git"
  "gnupg"
  "grep"
  "httpie"
  "imagemagick"
  "mas"
  "node"
  "openssh"
  "pinentry-mac"
  "postgresql"
  "ripgrep"
  "thefuck"
  "vim"
  "wget"
  "yarn"
)

applications=(
  "1password"
  "1password-cli"
  "brave-browser"
  "cleanmymac"
  "coda"
  "codekit"
  "docker"
  "figma"
  "firefox"
  "firefox-developer-edition"
  "github"
  "google-chrome-dev"
  "gpg-suite"
  "graphiql"
  "imageoptim"
  "iterm2"
  "ivpn"
  "keybase"
  "ledger-live"
  "little-snitch"
  "mamp"
  "pgadmin4"
  "postgres"
  "postman"
  "resilio-sync"
  "slack"
  "spotify"
  "the-unarchiver"
  "tor-browser"
  "transmission"
  "visual-studio-code"
  "vlc"
)

drivers=(
  "adoptopenjdk8"
  "ubiquiti-unifi-controller"
  "wacom-tablet"
)

fonts=(
  "font-cascadia-mono"
  "font-fira-code"
  "font-hack"
  "font-hind"
  "font-inconsolata"
  "font-input"
  "font-inter"
  "font-jetbrains-mono"
  "font-lato"
  "font-open-sans"
  "font-open-sans-condensed"
  "font-roboto"
  "font-roboto-mono"
  "font-roboto-slab"
  "font-source-sans-pro"
  "font-source-serif-pro"
)

# ========================================================================================
# Helpers
# ========================================================================================

install_homebrew() {
  printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Installing${NORMAL}\n"

  if [[ $(which brew) ]]; then
    printf "Homebrew installed.\n\n"

    printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Updating${NORMAL}\n"
    brew update
    brew upgrade
    printf "\n"
  else
    /usr/bin/env bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

    brew tap homebrew/cask-versions
    brew tap homebrew/cask-drivers
    brew tap homebrew/cask-fonts

    brew services

    brew analytics off
  fi
}

install_formulae() {
  for formula in ${formulae[@]}; do
    printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Installing formula ${GREEN}${formula}${NORMAL}\n"

    if [[ $(brew list --versions ${formula} 2> /dev/null) ]]; then
      printf "Formula installed.\n"
    else
      brew install ${formula}
    fi

    printf "\n"
  done
  unset formula
}

install_applications() {
  for application in ${applications[@]}; do
    printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Installing application ${GREEN}${application}${NORMAL}\n"

    if [[ $(brew cask list --versions ${application} 2> /dev/null) ]]; then
      printf "Application installed.\n"
    else
      brew cask install ${application}
    fi

    printf "\n"
  done
  unset application
}

install_drivers() {
  for driver in ${drivers[@]}; do
    printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Installing driver ${GREEN}${driver}${NORMAL}\n"

    if [[ $(brew cask list --versions ${driver} 2> /dev/null) ]]; then
      printf "Driver installed.\n"
    else
      brew cask install ${driver}
    fi

    printf "\n"
  done
  unset driver
}

install_fonts() {
  for font in ${fonts[@]}; do
    printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Installing font ${GREEN}${font}${NORMAL}\n"

    if [[ $(brew cask list --versions ${font} 2> /dev/null) ]]; then
      printf "Font installed.\n"
    else
      brew cask install ${font}
    fi

    printf "\n"
  done
  unset font
}

# ========================================================================================
# Homebrew
# ========================================================================================

install_homebrew
install_formulae
install_applications
install_drivers
install_fonts

printf "${BOLD}${PURPLE}==> [Homebrew]${NORMAL} ${BOLD}Cleaning up${NORMAL}\n"
brew cleanup
printf "Done.\n\n"
