#!/usr/bin/env bash

# ========================================================================================
# Aliases
# ========================================================================================

# alias the sudo command
alias _="sudo"

# alias the editor
alias edit=$EDITOR

# ========================================================================================
# Command Defaults
# ========================================================================================

# set default `cp` behavior to be verbose and to prompt if copy would cause overwrite
alias cp="cp -iv"

# set default `ln` behavior to be verbose
alias ln="ln -v"

# set default `mkdir` behavior to create intermediate directories as required
alias mkdir="mkdir -p"

# set default `mv` behavior to be verbose and to prompt if move would cause overwrite
alias mv="mv -iv"

# ========================================================================================
# Helpers
# ========================================================================================

# list current paths
alias paths="echo \"${PATH//:/$'\n'}\""

# reload profile
alias reload="source ~/.bash_profile"

# update everything
alias updateglobal="macupdate; asdfupdate; brewupdate; yarnglobal; gemglobal"
alias updatelocal="yarnlocal; gemlocal"

# ========================================================================================
# Shortcuts
# ========================================================================================

# directory navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

# common folders
alias desktop="cd ~/Desktop"
alias documents="cd ~/Documents"
alias downloads="cd ~/Downloads"
