#!/usr/bin/env bash

# ========================================================================================
# Completion
# ========================================================================================

# source all bash completions supplied by brew
if [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]]; then
  source "$(brew --prefix)/etc/profile.d/bash_completion.sh"
fi
