#!/usr/bin/env bash

# ========================================================================================
# Exports
# ========================================================================================

# output colors
export CLICOLOR=1
export LSCOLORS=ExFxBxDxCxegedabagacad
