#!/usr/bin/env bash

# ========================================================================================
# Git Functions (Credit to Zach Holman)
# https://github.com/holman/dotfiles/blob/master/zsh/prompt.zsh
# ========================================================================================

git_prompt_info() {
  ref=$(git symbolic-ref HEAD 2>/dev/null) || return
  echo "${ref#refs/heads/}"
}

git_status() {
  if git branch &> /dev/null; then
    if git status | grep "nothing to commit" &> /dev/null; then
      echo -en $GREEN$(__git_ps1 " [%s]")$RESET
    else
      echo -en $RED$(__git_ps1 " [%s]")$RESET
    fi
  fi
}

# ========================================================================================
# Path Functions (Credit to Anish Athalye)
# https://github.com/anishathalye/dotfiles/blob/master/shell/functions.sh
# ========================================================================================

path_remove() {
  PATH=$(echo -n "$PATH" | awk -v RS=: -v ORS=: "\$0 != \"$1\"" | sed 's/:$//')
}

path_append() {
  path_remove "$1"
  PATH="${PATH:+"$PATH:"}$1"
}

path_prepend() {
  path_remove "$1"
  PATH="$1${PATH:+":$PATH"}"
}
