#!/usr/bin/env bash

# ========================================================================================
# Prompt
# ========================================================================================

# reset color
RESET="\[\033[0m\]"

# regular
BLACK="\[\033[0;30m\]"
RED="\[\033[0;31m\]"
GREEN="\[\033[0;32m\]"
YELLOW="\[\033[0;33m\]"
BLUE="\[\033[0;34m\]"
PURPLE="\[\033[0;35m\]"
CYAN="\[\033[0;36m\]"
WHITE="\[\033[0;37m\]"

# bold
B_BLACK="\[\033[1;30m\]"
B_RED="\[\033[1;31m\]"
B_GREEN="\[\033[1;32m\]"
B_YELLOW="\[\033[1;33m\]"
B_BLUE="\[\033[1;34m\]"
B_PURPLE="\[\033[1;35m\]"
B_CYAN="\[\033[1;36m\]"
B_WHITE="\[\033[1;37m\]"

# underline
U_BLACK="\[\033[4;30m\]"
U_RED="\[\033[4;31m\]"
U_GREEN="\[\033[4;32m\]"
U_YELLOW="\[\033[4;33m\]"
U_BLUE="\[\033[4;34m\]"
U_PURPLE="\[\033[4;35m\]"
U_CYAN="\[\033[4;36m\]"
U_WHITE="\[\033[4;37m\]"

# background
BG_BLACK="\[\033[40m\]"
BG_RED="\[\033[41m\]"
BG_GREEN="\[\033[42m\]"
BG_YELLOW="\[\033[43m\]"
BG_BLUE="\[\033[44m\]"
BG_PURPLE="\[\033[45m\]"
BG_CYAN="\[\033[46m\]"
BG_WHITE="\[\033[47m\]"

# intense
I_BLACK="\[\033[0;90m\]"
I_RED="\[\033[0;91m\]"
I_GREEN="\[\033[0;92m\]"
I_YELLOW="\[\033[0;93m\]"
I_BLUE="\[\033[0;94m\]"
I_PURPLE="\[\033[0;95m\]"
I_CYAN="\[\033[0;96m\]"
I_WHITE="\[\033[0;97m\]"

# bold intense
BI_BLACK="\[\033[1;90m\]"
BI_RED="\[\033[1;91m\]"
BI_GREEN="\[\033[1;92m\]"
BI_YELLOW="\[\033[1;93m\]"
BI_BLUE="\[\033[1;94m\]"
BI_PURPLE="\[\033[1;95m\]"
BI_CYAN="\[\033[1;96m\]"
BI_WHITE="\[\033[1;97m\]"

# intense background
BG_IBLACK="\[\033[0;100m\]"
BG_IRED="\[\033[0;101m\]"
BG_IGREEN="\[\033[0;102m\]"
BG_IYELLOW="\[\033[0;103m\]"
BG_IBLUE="\[\033[0;104m\]"
BG_IPURPLE="\[\033[10;95m\]"
BG_ICYAN="\[\033[0;106m\]"
BG_IWHITE="\[\033[0;107m\]"

# variables
DATE="\d"
DIRECTORY="\w"
MACHINE="\h"
NEWLINE="\n"
TIME="\T"

# output
export PS1="$I_BLACK$DIRECTORY$RESET$(git_status)\n-> $RESET"
# "$I_BLACK[$USER@$MACHINE] $TIME $WHITE$DIRECTORY$RESET$(git_status) \$ $RESET"
