#!/usr/bin/env bash

# ========================================================================================
# Helpers
# ========================================================================================

# update rubygems
# update outdated gems
# cleanup stale/outdated/old gems
alias gemupdate="gem update --system; gem update; gem cleanup"
