#!/usr/bin/env zsh

# ========================================================================================
# Aliases
# ========================================================================================

# set exa as the default `ls` command
alias ls="exa --all --classify --extended --git --group --header --long"
