#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# GPG Keys
# ========================================================================================

printf "${BOLD}${PURPLE}==> [GNU Privacy Guard]${NORMAL} ${BOLD}Generating GPG keys${NORMAL}\n"

# generate GPG key
gpg_generate_key

# add pinentry-mac as the default GPG pinentry program
entry="pinentry-program /usr/local/bin/pinentry-mac"
file=~/.gnupg/gpg-agent.conf

if [[ ! $(grep ${entry} ${file}) ]]; then
  echo ${entry} > ${file}
fi

unset entry
unset file

printf "Done.\n\n"
