#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# GPG Keys
# ========================================================================================

printf "${BOLD}${PURPLE}==> [GNU Privacy Guard]${NORMAL} ${BOLD}Generating GPG keys${NORMAL}\n"

# generate GPG key
gpg_generate_key

printf "Done.\n\n"
