#!/usr/bin/env zsh

# ========================================================================================
# GPG Keys
# ========================================================================================

printf "${FG_MAGENTA}==> [GNU Privacy Guard] Generating GPG keys${RESET}\n"

# generate GPG key
gpg_generate_key

printf "Done.\n\n"
