#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# macOS Software Update
# ========================================================================================

sudo softwareupdate --install --all --background

# ========================================================================================
# macOS Config
# ========================================================================================

pkill -x "System Preferences"

# Setup some basic configuration and hard-to-reach settings. Found it was better to leave
# well enough alone and do most config through the GUI.

# ========================================================================================
# Network
# ========================================================================================

printf "${BOLD}${PURPLE}==> [macOS]${NORMAL} ${BOLD}Setting Network preferences${NORMAL}\n"

# enable airdrop over ethernet and on unsupported macs
defaults write com.apple.NetworkBrowser BrowseAllInterfaces -bool true

# ========================================================================================
# Finder
# ========================================================================================

printf "${BOLD}${PURPLE}==> [macOS]${NORMAL} ${BOLD}Setting Finder preferences${NORMAL}\n"

# show the ~/Library folder
chflags nohidden ~/Library

# ========================================================================================
# Restart
# ========================================================================================

printf "${BOLD}${PURPLE}==> [macOS]${NORMAL} ${BOLD}Restarting affected applications${NORMAL}\n"

killall Dock
killall Finder
killall SystemUIServer

# ========================================================================================
# App Store
# ========================================================================================

printf "${BOLD}${PURPLE}==> [macOS]${NORMAL} ${BOLD}Installing App Store software${NORMAL}\n"

mas install 420212497 # Byword
mas install 405772121 # LittleIpsum
mas install 497799835 # Xcode


# ========================================================================================
# App Store
# ========================================================================================

printf "${BOLD}${PURPLE}==> [macOS]${NORMAL} ${BOLD}Rebuilding Spotlight index${NORMAL}\n"

sudo mdutil -E /

printf "Done.\n\n"
