#!/usr/bin/env zsh

# ========================================================================================
# Local Environment
# ========================================================================================

printf "${FG_MAGENTA}==> [Environment] Configuring local environment${RESET}\n"

read "?Git Name: " _git_name
read "?Git Email: " _git_email
read "?Git Signing Key: " _git_signing_key

printf "${FG_MAGENTA}==> [Environment] Creating ${FG_BOLD_GREEN}~/.local/profile${RESET}\n"

touch ~/.local/profile
cat >> ~/.local/profile <<EOF
#!/usr/bin/env zsh

# ========================================================================================
# Variables
# ========================================================================================

# development
export EDITOR="code" # "vsc" also works
export BROWSER="brave"

# git information
export GIT_NAME="$_git_name"
export GIT_EMAIL="$_git_email"
export GIT_SIGNING_KEY="$_git_signing_key"

EOF

printf "Done.\n\n"
