#!/usr/bin/env zsh

# ========================================================================================
# Helpers
# ========================================================================================

# iOS simulator
alias simulate="open /Applications/Xcode.app/Contents/Developer/Applications/Simulator.app"
