#!/usr/bin/env zsh

# ========================================================================================
# Variables
# ========================================================================================

languages=(
  "erlang"
  "elixir"
  "python"
  "ruby"
)

# ========================================================================================
# Helpers
# ========================================================================================

function install_languages() {
  for language in "${languages[@]}"; do
    printf "${FG_MAGENTA}==> [asdf] Installing package ${FG_BOLD_GREEN}${language}${RESET}\n"

    # ensure the language plugin is installed and up to date
    if [[ $(asdf plugin list | grep -i ${language}) ]]; then
      asdf plugin update ${language} &> /dev/null
      printf "${language} plugin is up to date.\n"
    else
      printf "${FG_MAGENTA}==> Installing ${language} plugin${RESET}\n"
      asdf plugin add ${language}
    fi

    latest="$(asdf latest ${language})"

    # ensure the latest version of the language is installed
    if [[ $(asdf list ${language} 2> /dev/null | grep -i ${latest}) ]]; then
      printf "${language} version ${latest} is installed.\n"
    else
      printf "${FG_MAGENTA}==> Installing ${language} version ${latest}${RESET}\n"
      asdf install ${language} latest
    fi

    # ensure the latest version of the language is set globally
    if [[ $(asdf current ${language} | grep -i ${latest}) ]]; then
      printf "${language} version ${latest} is set globally.\n"
    else
      printf "${FG_MAGENTA}==> Setting global ${language} version to ${latest}${RESET}\n"
      asdf global ${language} ${latest}
    fi

    printf "\n"
  done
  unset language
  unset latest
}

# ========================================================================================
# asdf
# ========================================================================================

install_languages
