#!/usr/bin/env zsh

# ========================================================================================
# Aliases
# ========================================================================================

# alias the sudo command
alias _="sudo"

# alias the editor
alias edit=${EDITOR}

# ========================================================================================
# Command Defaults
# ========================================================================================

# set default `cp` behavior to be verbose and to prompt if copy would cause overwrite
alias cp="cp -iv"

# set default `ln` behavior to be verbose
alias ln="ln -v"

# set default `mkdir` behavior to create intermediate directories as required
alias mkdir="mkdir -p"

# set default `mv` behavior to be verbose and to prompt if move would cause overwrite
alias mv="mv -iv"

# set default `rm` behavior to be verbose and to prompt for confirmation before removal
alias rm="rm -iv"

# set default `df` behavior to show human readable sizes
alias df="df -H"

# ========================================================================================
# Helpers
# ========================================================================================

# list current paths
alias paths="echo \"${PATH//:/$'\n'}\""

# reload shell
alias reload="source ~/.zshrc"

# update everything
alias updatesystem="osupdate; asdfupdate; brewupdate"

# ========================================================================================
# Shortcuts
# ========================================================================================

# directory navigation
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
