#!/usr/bin/env zsh

# ========================================================================================
# Dotfiles
# ========================================================================================

# load private environment
if [[ -r ~/.local/profile ]]; then
  source ~/.local/profile
fi

# load dotfile configurations
for file in ~/.dotfiles/**/config; do
	if [[ -r ${file} ]]; then
    source ${file}
  fi
done
unset file
