#!/usr/bin/env zsh

# ========================================================================================
# Paths
# ========================================================================================

. /opt/homebrew/opt/asdf/libexec/asdf.sh

path_prepend ~/.local/bin

if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh-completions:${FPATH}
fi
