#!/usr/bin/env zsh

source ~/.dotfiles/zsh/sources/eval
source ~/.dotfiles/zsh/sources/exports
source ~/.dotfiles/zsh/sources/functions
source ~/.dotfiles/zsh/sources/paths
source ~/.dotfiles/zsh/sources/prompt
source ~/.dotfiles/zsh/sources/options
source ~/.dotfiles/zsh/sources/plugins
source ~/.dotfiles/zsh/sources/aliases
source ~/.dotfiles/zsh/sources/hotkeys
source ~/.dotfiles/zsh/sources/dotfiles

# pnpm
export PNPM_HOME="/Users/drew/Library/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME:"*) ;;
  *) export PATH="$PNPM_HOME:$PATH" ;;
esac
# pnpm end
# bun completions
[ -s "/Users/drew/.bun/_bun" ] && source "/Users/drew/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"
