#!/usr/bin/env bash

# ========================================================================================
# Aliases
# ========================================================================================

alias bt="brew tap"
alias bi="brew install"
alias bci="brew cask install"
alias blv="brew list --versions"
alias bclv="brew cask list --versions"

# ========================================================================================
# Helpers
# ========================================================================================

# update homebrew and formulae
# upgrade outdated formulae
# remove stale/outdated/old formulae
alias brewupdate="brew update; brew upgrade; brew cleanup"
