#!/usr/bin/env zsh

# ========================================================================================
# Aliases
# ========================================================================================

alias bt="brew tap"
alias bi="brew install"
alias bic="brew install --cask"
alias blv="brew list --versions"
alias blcv="brew list --cask --versions"

# ========================================================================================
# Helpers
# ========================================================================================

# update homebrew and formulae
# upgrade outdated formulae
# remove stale/outdated/old formulae
alias brewupdate="brew update; brew upgrade; brew cleanup"
