#!/usr/bin/env zsh

# ========================================================================================
# Aliases
# ========================================================================================

# set eza as the default `ls` command
alias ls="eza --all --classify --extended --git --group --header --long"
