#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# Git
# ========================================================================================

printf "${BOLD}${PURPLE}==> [Git]${NORMAL} ${BOLD}Creating ${GREEN}~/.gitconfig.local${NORMAL}\n"
touch ~/.gitconfig.local
cat >> ~/.gitconfig.local <<EOF
[user]

  name = $GIT_NAME
  email = $GIT_EMAIL
  signingkey = $GIT_SIGNING_KEY

EOF
printf "Done.\n\n"
