#!/usr/bin/env zsh

# ========================================================================================
# Git
# ========================================================================================

printf "${FG_MAGENTA}==> [Git] Creating ${FG_BOLD_GREEN}~/.gitconfig.local${RESET}\n"
rm ~/.gitconfig.local
touch ~/.gitconfig.local
cat >> ~/.gitconfig.local <<EOF
[user]

  name = ${GIT_NAME}
  email = ${GIT_EMAIL}
  signingKey = ${GIT_SIGNING_KEY}

EOF
printf "Done.\n\n"
