#!/usr/bin/env bash

source ${BASH_SOURCE%/*}/../bash/sources/colors

# ========================================================================================
# Variables
# ========================================================================================

packages=(
  "@vue/cli"
  "babel-eslint"
  "create-react-app"
  "eslint"
  "fkill-cli"
  "json-server"
  "lighthouse"
  "spoof"
  "stylelint"
  "tldr"
  "typescript"
)

# ========================================================================================
# Helpers
# ========================================================================================

install_packages() {
  for package in ${packages[@]}; do
    printf "${BOLD}${PURPLE}==> [Yarn]${NORMAL} ${BOLD}Installing package ${GREEN}${package}${NORMAL}\n"

    yarn global add ${package}

    printf "\n"
  done
  unset package
}

# ========================================================================================
# Yarn
# ========================================================================================

install_packages
